Account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('login', views.UserLoginView.as_view(), name='login'),
    path('otp_login', views.OtpLoginView.as_view(), name='otp_login_request'),
    path('check_otp_login', views.CheckOtpLoginView.as_view(), name='check_otp_login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('check_otp', views.CheckOtpView.as_view(), name='check_otp'),
    path('logout', views.UserLogoutView.as_view(), name='logout'),
    path('reset_password_request', views.ResetPasswordRequestView.as_view(), name='reset_password_request'),
    path('reset_password_confirm', views.ResetPasswordConfirmView.as_view(), name='reset_password_confirm'),
    path('reset-password-complete/', views.ResetPasswordCompleteView.as_view(), name='reset_password_complete'),
    path('add_address', views.AddAddressView.as_view(), name='add_address'),
    path('profile/<str:slug>', views.UserProfileView.as_view(), name='profile'),
    path('profile/edit/photo/<str:slug>', views.UserProfilePhotoEditView.as_view(), name='profile_edit_photo'),
    path('profile/edit/fullname/<str:slug>', views.UserProfileFullnameEditView.as_view(), name='profile_edit_fullname'),
    path('profile/edit/email/<str:slug>', views.UserProfileEmailEditView.as_view(), name='profile_edit_email'),
    path('profile/edit/bio/<str:slug>', views.UserProfileBioEditView.as_view(), name='profile_edit_bio'),


]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('account/', include('Account.urls')),
    path('contactus/', include('contactus.urls')),
    path('cart/', include('cart.urls')),
    path('zarinpal/', include('zarinpal.urls')),
    path('chatuser/', include('chatuser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_add'),
    path('delete/<str:id>', views.CartDeleteView.as_view(), name='cart_delete'),
    path('update/', views.update_cart_item_quantity, name='update_cart_item_quantity'),
    path('calculate-total-with-shipping/', views.calculate_total_with_shipping, name='calculate_total_with_shipping'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/add', views.OrderCreationView.as_view(), name='order_creation'),
    path('discount/<int:pk>', views.ApplyDiscount.as_view(), name='discount'),
]

zarinpal/urls.py
from django.urls import path
from . import views

app_name = 'zarinpal'

urlpatterns = [
    path('request/payment/<int:pk>', views.SendRequestPayment.as_view(), name='request_payment'),
    path('verify/', views.VerifyView.as_view(), name='verify_payment'),
]

cart/models.py
from django.db import models
from Account.models import User
from product.models import Product, Color, Size


class Shipping(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'حمل و نقل'
        verbose_name_plural = 'حمل و نقل ها'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    total_price = models.IntegerField(default=0, verbose_name="کل خرید")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')
    shipping_type = models.CharField(max_length=30,blank=True,null=True,verbose_name="نوع ارسال")
    shipping_price = models.IntegerField(default=0,verbose_name='هزینه ارسال')
    total_price = models.IntegerField(default=0, verbose_name="مبلغ کل")
    is_paid = models.BooleanField(default=False, verbose_name='وضعیت پرداخت')
    address = models.TextField(null=True,blank=True)

    def __str__(self):
        return f'{self.user.phone}-{self.user.fullname}'

    class Meta:
        verbose_name_plural = "سفارشات"
        verbose_name = "سفارش"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='سفارش')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='items', verbose_name='محصول')
    size = models.CharField(null=True,blank=True,max_length=12, verbose_name='سایز')
    color = models.CharField(null=True,blank=True,max_length=12, verbose_name='رنگ')
    quantity = models.SmallIntegerField(verbose_name='تعداد')
    price = models.PositiveIntegerField(verbose_name='قیمت')
    total = models.PositiveIntegerField(default=0,verbose_name='جمع')


    def __str__(self):
        return f'{self.product.title} - {self.color} - {self.size} - {self.quantity}'

    class Meta:
        verbose_name_plural = "اقلام سفارش"
        verbose_name = "نوع سفارش"



class DiscountCode(models.Model):
    title = models.CharField(max_length=100,unique=True,verbose_name='عنوان')
    percentage = models.SmallIntegerField(default=0,verbose_name='درصد')
    quantity = models.SmallIntegerField(default=0,verbose_name='تعداد')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'تخفیف'
        verbose_name_plural = 'تخفیفات'


class UsedDiscount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='کاربر')
    discount = models.ForeignKey(DiscountCode, on_delete=models.CASCADE,verbose_name='کد تخفیف')
    used_at = models.DateTimeField(auto_now_add=True,verbose_name='استفاده شده')

    def __str__(self):
        return f'{str(self.user)} - {self.discount}'

    class Meta:
        unique_together = ('user', 'discount')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.http import JsonResponse
from product.models import Product
from .cart_module import Cart
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from .models import Shipping, Order, OrderItem, UsedDiscount
from cart.models import DiscountCode



class CartDetailView(View):
    def get(self,request):
        cart = Cart(request)
        shippings = Shipping.objects.all()
        return render(request,'cart/cart_detail.html',{'cart':cart,'shippings':shippings})


class CartAddView(View):
    def post(self,request, pk):
        product = get_object_or_404(Product,pk=pk)
        size, color, quantity = request.POST.get('size'), request.POST.get('color'), request.POST.get('quantity')
        cart = Cart(request)
        cart.add(product, size, color, quantity)
        return redirect('cart:cart_detail')


class CartDeleteView(View):
    def get(self, request, id, *args, **kwargs):
        cart = Cart(request)
        cart.delete(id)
        return redirect("cart:cart_detail")



@require_POST
@csrf_exempt
def update_cart_item_quantity(request):
    unique_id = request.POST.get('unique_id')
    action = request.POST.get('action')
    cart = Cart(request)

    if action == 'increase':
        cart.update_quantity(unique_id, 1)
    elif action == 'decrease':
        cart.update_quantity(unique_id, -1)

    shipping_title = request.POST.get('shipping_title')
    cart_sub_total = cart.sub_total()
    cart_shipping = cart.shipping() if shipping_title == 'Post' else 0
    item = cart.cart[unique_id]
    item_total = int(item['quantity']) * int(item['price'])
    cart_total = cart.total(shipping_title)

    return JsonResponse({
        'quantity': item['quantity'],
        'item_total': item_total,
        'cart_sub_total': cart_sub_total,
        'shipping': cart_shipping,
        'cart_total': cart_total,
    })



@require_POST
@csrf_exempt
def calculate_total_with_shipping(request):
    shipping_title = request.POST.get('shipping_title')
    cart = Cart(request)
    total_with_shipping = cart.total(shipping_title)
    return JsonResponse({'total_with_shipping': total_with_shipping})



class OrderDetailView(View):
    def get(self,request,pk):
        order = Order.objects.get(id=pk)
        return render(request, 'cart/order_detail.html', {'order':order})


class OrderCreationView(LoginRequiredMixin,View):
    def get(self,request):
        cart = Cart(request)
        shiping = request.GET.get('shiping')
        shipping_cost = cart.shipping() if shiping == 'Post' else 0
        total_price = cart.total(shiping)
        order = Order.objects.create(user=request.user,total_price=total_price, shipping_type=shiping,shipping_price=shipping_cost)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], color=item['color'], size=item['size'],
                                     price=item['price'], quantity=item['quantity'],total=item['total'])
        cart.remove_cart()
        return redirect('cart:order_detail', order.id)


class ApplyDiscount(View):
    def post(self, request, pk):
        discount_code = request.POST.get('discount_code')
        order = get_object_or_404(Order, pk=pk)
        discount = get_object_or_404(DiscountCode, title=discount_code)

        # چک کردن اینکه آیا کاربر قبلاً از این کد تخفیف استفاده کرده است یا خیر
        if UsedDiscount.objects.filter(user=request.user, discount=discount).exists():
            return redirect('cart:order_detail', order.id)

        if discount.quantity == 0:
            return redirect('cart:order_detail', order.id)

        order.total_price -= order.total_price * discount.percentage / 100
        order.save()

        discount.quantity -= 1
        discount.save()

        # ذخیره استفاده از کد تخفیف برای این کاربر
        UsedDiscount.objects.create(user=request.user, discount=discount)

        return redirect('cart:order_detail', order.id)

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="container-fluid">
        {% if not cart.cart %}
            <div class="row justify-content-center">
                <div class="col-lg-6 text-center">
                    <img src="{% static 'img/cart.jpg' %}" alt="Empty Cart" style="width: 100%; max-width: 400px;">
                    <h3 class="mt-3">چیزی در سبد خرید وجود ندارد</h3>
                </div>
            </div>
        {% else %}
            <div class="row px-xl-5">
                <div class="col-lg-8 table-responsive mb-5">
                    <table class="table table-light table-borderless table-hover text-center mb-0">
                        <thead class="thead-dark">
                        <tr>
                            <th>Images</th>
                            <th>Title</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                        </thead>

                        <tbody class="align-middle">
                        {% for item in cart %}
                            <tr>
                                <td class="align-middle"><img src="{{ item.product.image.url }}" alt="" style="width: 50px;"></td>
                                <td class="align-middle">{{ item.product.title }}</td>
                                <td class="align-middle">${{ item.price }}</td>
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-primary btn-minus" data-action="decrease"
                                                    data-unique-id="{{ item.unique_id }}">
                                                <i class="fa fa-minus"></i>
                                            </button>
                                        </div>
                                        <input type="text"
                                               class="form-control form-control-sm bg-secondary border-0 text-center"
                                               value="{{ item.quantity }}" data-unique-id="{{ item.unique_id }}">
                                        <div class="input-group-btn">
                                            <button data-action="increase" type="button"
                                                    class="btn btn-sm btn-primary btn-plus"
                                                    data-unique-id="{{ item.unique_id }}">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">{{ item.color }}</td>
                                <td class="align-middle">{{ item.size }}</td>
                                <td class="align-middle" data-unique-id="{{ item.unique_id }}">${{ item.total }}</td>
                                <td class="align-middle">
                                    <a href="{% url 'cart:cart_delete' item.unique_id %}" class="btn btn-sm btn-danger">
                                        <i class="fa fa-times"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>
                {% if cart.cart %}
                    <div class="col-lg-4">
                        <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                        <div class="bg-light p-30 mb-5">
                            <div class="border-bottom pb-2">
                                <div class="d-flex justify-content-between mb-3">
                                    <h6>Subtotal</h6>
                                    <h6 id="factor-sub-total">${{ cart.sub_total }}</h6>
                                </div>
                                <div class="d-flex mb-3">
                                    <strong class="text-dark mr-3">Shipping type</strong>
                                    {% csrf_token %}
                                    {% for ship in shippings.all %}
                                        <div class="custom-control custom-radio custom-control-inline">
                                            <input type="radio" class="custom-control-input" id="shiping-{{ forloop.counter }}"
                                                   name="shiping" value="{{ ship.title }}" {% if forloop.first %}checked{% endif %}>
                                            <label class="custom-control-label" for="shiping-{{ forloop.counter }}">{{ ship.title }}</label>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="d-flex justify-content-between">
                                    <h6 class="font-weight-medium">Shipping</h6>
                                    <h6 id="factor-shipping" class="font-weight-medium">${{ cart.shipping }}</h6>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between mt-2">
                                <h5>Total</h5>
                                <h5 id="factor-total">${{ cart.total }}</h5>
                            </div>
                            <a id="checkout-link" href="{% url 'cart:order_creation' %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">
                                Proceed To Checkout
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            function checkShippingVisibility() {
                var selectedShipping = $('input[name="shiping"]:checked').val();

                $.ajax({
                    url: "{% url 'cart:calculate_total_with_shipping' %}",
                    type: 'POST',
                    data: {
                        'shipping_title': selectedShipping,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        var shippingCost = response.total_with_shipping - $('#factor-sub-total').text().replace('$', '');

                        if (shippingCost == 0) {
                            $('#factor-shipping').hide();
                        } else {
                            $('#factor-shipping').show();
                            $('#factor-shipping').text('$' + shippingCost);
                        }

                        $('#factor-total').text('$' + response.total_with_shipping);
                    }
                });
            }

            checkShippingVisibility();

            $('.btn-plus, .btn-minus').on('click', function () {
                var uniqueId = $(this).data('unique-id');
                var action = $(this).data('action');
                var shippingTitle = $('input[name="shiping"]:checked').val();

                $.ajax({
                    url: "{% url 'cart:update_cart_item_quantity' %}",
                    type: 'POST',
                    data: {
                        'unique_id': uniqueId,
                        'action': action,
                        'shipping_title': shippingTitle,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        $('input[data-unique-id="' + uniqueId + '"]').val(response.quantity);
                        $('td[data-unique-id="' + uniqueId + '"]').text('$' + response.item_total);
                        $('#factor-sub-total').text('$' + response.cart_sub_total);
                        $('#factor-shipping').text('$' + response.shipping);
                        $('#factor-total').text('$' + response.cart_total);

                        checkShippingVisibility();
                    }
                });
            });

            $('input[name="shiping"]').on('change', function () {
                var shippingTitle = $(this).val();

                $.ajax({
                    url: "{% url 'cart:calculate_total_with_shipping' %}",
                    type: 'POST',
                    data: {
                        'shipping_title': shippingTitle,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        $('#factor-total').text('$' + response.total_with_shipping);
                        checkShippingVisibility();
                    }
                });
            });
        });

        document.getElementById('checkout-link').addEventListener('click', function(event) {
            event.preventDefault();

            const shippingOption = document.querySelector('input[name="shiping"]:checked').value;
            const url = "{% url 'cart:order_creation' %}?shiping=" + encodeURIComponent(shippingOption);

            window.location.href = url;
        });
    </script>
{% endblock %}

cart/templates/cart/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <!-- Checkout Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Billing Address</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label>First Name</label>
                            <input class="form-control" type="text" placeholder="John">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Last Name</label>
                            <input class="form-control" type="text" placeholder="Doe">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>E-mail</label>
                            <input class="form-control" type="text" placeholder="example@email.com">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Mobile No</label>
                            <input class="form-control" type="text" placeholder="+123 456 789">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address Line 1</label>
                            <input class="form-control" type="text" placeholder="123 Street">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address Line 2</label>
                            <input class="form-control" type="text" placeholder="123 Street">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Country</label>
                            <select class="custom-select">
                                <option selected>United States</option>
                                <option>Afghanistan</option>
                                <option>Albania</option>
                                <option>Algeria</option>
                            </select>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>City</label>
                            <input class="form-control" type="text" placeholder="New York">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>State</label>
                            <input class="form-control" type="text" placeholder="New York">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>ZIP Code</label>
                            <input class="form-control" type="text" placeholder="123">
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="newaccount">
                                <label class="custom-control-label" for="newaccount">Create an account</label>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="shipto">
                                <label class="custom-control-label" for="shipto" data-toggle="collapse"
                                       data-target="#shipping-address">Ship to different address</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="collapse mb-5" id="shipping-address">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Shipping Address</span>
                    </h5>
                    <div class="bg-light p-30">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label>First Name</label>
                                <input class="form-control" type="text" placeholder="John">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Last Name</label>
                                <input class="form-control" type="text" placeholder="Doe">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>E-mail</label>
                                <input class="form-control" type="text" placeholder="example@email.com">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Mobile No</label>
                                <input class="form-control" type="text" placeholder="+123 456 789">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Address Line 1</label>
                                <input class="form-control" type="text" placeholder="123 Street">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Address Line 2</label>
                                <input class="form-control" type="text" placeholder="123 Street">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Country</label>
                                <select class="custom-select">
                                    <option selected>United States</option>
                                    <option>Afghanistan</option>
                                    <option>Albania</option>
                                    <option>Algeria</option>
                                </select>
                            </div>
                            <div class="col-md-6 form-group">
                                <label>City</label>
                                <input class="form-control" type="text" placeholder="New York">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>State</label>
                                <input class="form-control" type="text" placeholder="New York">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>ZIP Code</label>
                                <input class="form-control" type="text" placeholder="123">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <form method="post" class="mb-30" action="{% url 'cart:discount' order.id %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input name="discount_code" type="text" class="form-control border-0 p-4"
                               placeholder="Discount Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Order Total</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom">
                        <h6 class="mb-3">Products</h6>
                        {% for item in order.items.all %}
                            <div class="d-flex justify-content-between">
                                <p> 👚 {{ item.product.title }}</p>
                                <p> Total : ${{ item.total }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="border-bottom">
                        <h6 class="mb-3">Shipping</h6>
                        <div class="d-flex justify-content-between">
                            <p> 💸 Total</p>
                            <p>${{ order.shipping_price }}</p>
                        </div>
                        <div class="border-bottom">
                            <h6 class="mb-3">Factor</h6>
                            <div class="d-flex justify-content-between">
                                <p>💸 Total</p>
                                <p>${{ order.total_price }}</p>
                            </div>

                        </div>
                    </div>
                </div>
                {% if request.user.addresses.all %}
                    <form action="{% url 'zarinpal:request_payment' order.id %}" method="post">
                    {% csrf_token %}
                     <select name="address" class="form-control" aria-label="Default select example">
                        {% for address in request.user.addresses.all %}
                            <option value="{{ address.id }}">{{ address }}</option>
                        {% endfor %}
                    </select>
                        <button type="submit" class="btn btn-block btn-success font-weight-bold py-3 mt-3">Pay</button>
                    </form>
                       {% if not request.user.addresses.count == 2 %}
                         <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}" class="btn btn-block btn-warning font-weight-bold py-3 mt-2">Add Another Address</a>

                    {% endif %}
                {% else %}
                    <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}" class="btn btn-block btn-warning font-weight-bold py-3">You don't have an address, add one</a>

                {% endif %}
            </div>
        </div>
    </div>
    <!-- Checkout End -->


{% endblock %}