Account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('login', views.UserLoginView.as_view(), name='login'),
    path('otp_login', views.OtpLoginView.as_view(), name='otp_login_request'),
    path('check_otp_login', views.CheckOtpLoginView.as_view(), name='check_otp_login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('check_otp', views.CheckOtpView.as_view(), name='check_otp'),
    path('logout', views.UserLogoutView.as_view(), name='logout'),
    path('reset_password_request', views.ResetPasswordRequestView.as_view(), name='reset_password_request'),
    path('reset_password_confirm', views.ResetPasswordConfirmView.as_view(), name='reset_password_confirm'),
    path('reset-password-complete/', views.ResetPasswordCompleteView.as_view(), name='reset_password_complete'),
    path('add_address', views.AddAddressView.as_view(), name='add_address'),
    path('profile/<str:slug>', views.UserProfileView.as_view(), name='profile'),
    path('profile/edit/photo/<str:slug>', views.UserProfilePhotoEditView.as_view(), name='profile_edit_photo'),
    path('profile/edit/fullname/<str:slug>', views.UserProfileFullnameEditView.as_view(), name='profile_edit_fullname'),
    path('profile/edit/email/<str:slug>', views.UserProfileEmailEditView.as_view(), name='profile_edit_email'),
    path('profile/edit/bio/<str:slug>', views.UserProfileBioEditView.as_view(), name='profile_edit_bio'),


]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('account/', include('Account.urls')),
    path('contactus/', include('contactus.urls')),
    path('cart/', include('cart.urls')),
    path('zarinpal/', include('zarinpal.urls')),
    path('chatuser/', include('chatuser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_add'),
    path('delete/<str:id>', views.CartDeleteView.as_view(), name='cart_delete'),
    path('update/', views.update_cart_item_quantity, name='update_cart_item_quantity'),
    path('calculate-total-with-shipping/', views.calculate_total_with_shipping, name='calculate_total_with_shipping'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/add', views.OrderCreationView.as_view(), name='order_creation'),
    path('discount/<int:pk>', views.ApplyDiscount.as_view(), name='discount'),
]

contactus/urls.py
from django.urls import path
from . import views
app_name = 'contactus'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contactus'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('<int:pk>', views.ProductDetail.as_view(), name="product_detail"),
    path('list', views.ProductListView.as_view(), name="product_list"),
    path('mainrender',views.CategoryRenderPartial.as_view(), name="main_render"),
    path("category/<slug:slug>", views.Category_detail, name="category_detail"),
    path("search/", views.SearchProductView.as_view(), name="search_products"),
    path('like/<int:pk>', views.LikeProductView.as_view(), name="like"),
    path('listlikers/<int:pk>', views.ProductLikers.as_view(), name="list_likers"),

]

templates/includes/footer.html
{% load static %}

 <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                    <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

templates/includes/footer_reference.html
{% load static %}


 <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/includes/head_reference.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>MultiShop - Online Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">  

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

templates/includes/navbar.html
{% load static %}
<style>
   
    @font-face {
        font-family: MyCustomFont;
        src: url("{% static 'fonts/Peyda-Medium[@fontbazi].ttf' %}") format("truetype");
        font-weight: normal;
        font-style: normal;
    }

    .nav-item.nav-link {
        font-family: MyCustomFont, sans-serif;
        font-size: 16px;
        color: #333; /* رنگ پیش‌فرض */
        transition: color 0.3s; /* تغییر رنگ به صورت انیمیشن */
    }
    
    .text-dark.m-0{
        font-family: MyCustomFont, sans-serif;
    }
    
</style>
<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse"
               href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light"
                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    <div class="nav-item dropdown dropright">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Dresses <i
                                class="fa fa-angle-right float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                            <a href="" class="dropdown-item">Men's Dresses</a>
                            <a href="" class="dropdown-item">Women's Dresses</a>
                            <a href="" class="dropdown-item">Baby's Dresses</a>
                        </div>
                    </div>
                    <a href="" class="nav-item nav-link">Shirts</a>
                    <a href="" class="nav-item nav-link">Jeans</a>
                    <a href="" class="nav-item nav-link">Swimwear</a>
                    <a href="" class="nav-item nav-link">Sleepwear</a>
                    <a href="" class="nav-item nav-link">Sportswear</a>
                    <a href="" class="nav-item nav-link">Jumpsuits</a>
                    <a href="" class="nav-item nav-link">Blazers</a>
                    <a href="" class="nav-item nav-link">Jackets</a>
                    <a href="" class="nav-item nav-link">Shoes</a>
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
                        <a href="{% url 'product:product_list' %}" class="nav-item nav-link">Shop</a>
                        <a href="{% url 'contactus:contactus' %}" class="nav-item nav-link">Contact</a>
                        <a href="" class="nav-item nav-link">About</a>
                    </div>
                </div>
                <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                    <a href="" class="btn px-0">
                        <i class="fas fa-heart text-primary"></i>
                        <span class="badge text-secondary border border-secondary rounded-circle"
                              style="padding-bottom: 2px;">0</span>
                    </a>
                    <a href="{% url 'cart:cart_detail' %}" class="btn px-0 ml-3">
                        <i class="fas fa-shopping-cart text-primary"></i>
                        {% if cart_item_count > 0 %}
                            <span class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;">{{ cart_item_count }}</span>
                        {% endif %}
                    </a>
                </div>
        </div>
        </nav>
    </div>
</div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // همه لینک‌ها با کلاس 'nav-link'
        const navLinks = document.querySelectorAll('.navbar-nav .nav-link');
        
        // دریافت لینک فعال از localStorage
        const activeLink = localStorage.getItem('activeLink');

        // اگر لینک فعال وجود دارد، به آن کلاس 'active' اضافه کن
        if (activeLink) {
            document.querySelector(`.navbar-nav .nav-link[href="${activeLink}"]`).classList.add('active');
        }

        // اضافه کردن event listener به لینک‌ها
        navLinks.forEach(link => {
            link.addEventListener('click', function () {
                // حذف کلاس 'active' از همه لینک‌ها
                navLinks.forEach(l => l.classList.remove('active'));

                // اضافه کردن کلاس 'active' به لینک کلیک‌شده
                this.classList.add('active');

                // ذخیره href لینک فعال در localStorage
                localStorage.setItem('activeLink', this.getAttribute('href'));
            });
        });
    });
</script>

<!-- Navbar End -->

templates/includes/top_bar.html
{% load static %}

<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                {% if request.user.is_authenticated %}
                <div><a href="{% url 'account:profile' request.user.slug %}" class="btn badge-success">{{ request.user.fullname }}</a></div>
                    {% else %}
                     <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My
                            Account
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <button class="dropdown-item" type="button"><a href="{% url 'account:login' %}">Sign in</a></button>
                            <button class="dropdown-item" type="button"><a href="{% url 'account:register' %}">Sign up</a></button>
                        </div>
                {% endif %}
            </div>
        </div>
                </div>
                </div>
                </div>
            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-heart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-shopping-cart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Multi</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form method="get" action="{% url 'product:search_products' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Search for products">
                    <div class="input-group-append">
                <span class="input-group-text bg-transparent text-primary">
                    <i class="fa fa-search"></i>
                </span>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Customer Service</p>
            <h5 class="m-0">+012 345 6789</h5>
        </div>
    </div>
</div>